name: Build Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar ambiente MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Instalar Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          arch: "win64_msvc2022_64"
          modules: qtmultimedia
          cache: true

      - name: Verificar versões
        shell: cmd
        run: |
          qmake -v
          cl

      - name: Gerar Makefile
        shell: cmd
        run: |
          qmake MemoryGame.pro CONFIG+=release

      - name: Compilar
        shell: cmd
        run: |
          nmake

      - name: Copiar DLLs do Qt
        shell: cmd
        run: |
          windeployqt release\MemoryGame.exe

      - name: Enviar executável
        uses: actions/upload-artifact@v4
        with:
          name: MemoryGame-Windows
          path: release
